-- 성경 질문 — 질문·응답 기록 · 관리자 열람 기록 · 고쳐 쓰는 목록 · 설교 색인 (2026-09-18)
--
-- 기준 문서: docs/BIBLE_QA_DOCTRINE.md (§B-10 기록 규칙) · docs/BIBLE_QA_SERMONS.md
--
-- 공통 정책 (scripts/migration-login-features.sql 과 동일)
--  * user_id 는 saint.yebom.org 의 text id. Supabase Auth 를 쓰지 않으므로 auth.uid() 는 항상 null.
--    그래서 RLS 를 켜되 정책은 두지 않는다 = anon/authenticated 는 아무것도 못 읽고 못 쓴다.
--    서버(supabaseAdmin, service_role)만 접근하며 항상 user_id 로 스코프한다.
--    **enable row level security 를 빠뜨리면 anon 키로 전 교인의 질문 내용이 그대로 노출된다.**
--    (anon 키는 NEXT_PUBLIC_ 이라 브라우저 번들에 실린다. 실제로 그 한 줄을 빠뜨려
--     열려 있는 표가 이 DB 에 이미 있다 — plan.md 의 RLS 점검 항목을 함께 볼 것.)
--  * user_id 에 FK 를 걸지 않는다 — 교인 계정 표가 이 스키마에 없다.
--  * id 는 bigint generated by default as identity (always 로 하면 id 를 실어 보내는 코드가 실패한다).
--  * UNIQUE 는 인라인 제약이 아니라 별도 create unique index — 같은 파일을 두 번 실행해도 안전해야 한다.
--  * 멱등 — 여러 번 실행해도 안전하다.

-- ══════════════════════════════════════════════════════════════════
-- 1. 질문 한 건 = 한 행
-- ══════════════════════════════════════════════════════════════════
create table if not exists public.ai_questions (
  id              bigint      generated by default as identity primary key,
  user_id         text        not null,
  -- 관리자 화면에 띄울 이름. 조인할 계정 표가 없어 질문 시점의 세션 이름을 복사해 둔다.
  user_name       text,

  -- 어느 절을 보고 물었는가 (§4 "질문에 다른 구절이 나오지 않으면 고른 본문을 두고 묻는 것으로 읽는다")
  book_code       varchar(10) not null,
  chapter         smallint    not null,
  verse_start     smallint    not null,
  verse_end       smallint,
  version         varchar(10),
  -- 화면·프롬프트에 그대로 쓰는 표기. 예: "누가복음 5:1-11"
  verses_ref      text,

  question        text        not null,
  -- 글로 물었나 말로 물었나 (말은 STT 를 거쳐 글이 된 것)
  input_kind      varchar(10) not null default 'text',

  -- 선별 결과: allow · deny · crisis · error(게이트 실패 → 통과시킨 건)
  gate_result     varchar(10) not null,
  -- 위기 건은 관리자 화면에서 눈에 띄게 표시해 super_admin 이 처리한다(§B-10).
  -- gate_result 와 따로 두는 까닭: 뒤에 사람이 '위기가 아니었다' 고 판정해도
  -- 그때 기계가 무엇으로 갈랐는지는 지워지지 않아야 한다.
  is_crisis       boolean     not null default false,
  -- 위기 판정을 사람이 검토한 결과. null = 아직 안 봤다
  crisis_reviewed boolean,
  crisis_note     text,

  -- single = 한 AI, chorus = 셋이 함께
  mode            varchar(10) not null default 'single',
  -- 가정교회 자료 블록을 붙여 보냈는가 (§B-12)
  housechurch     boolean     not null default false,

  -- 어떤 기준으로 답했는가 (§B-10 · §B-11). 문제가 된 답을 되짚을 수 있어야 한다.
  prompt_version  varchar(20) not null default 'v1',
  -- DB 에 둔 목록(이단·가정교회·위기창구·삶공부)의 갱신 시각
  lists_synced_at timestamptz,

  -- 교인이 저장을 눌렀는가. 교인이 지우면 false 로 내려가고 이 행은 남는다(§B-10).
  saved           boolean     not null default false,
  saved_at        timestamptz,

  asked_at        timestamptz not null default now()
);

-- 내 기록 조회(본인) + 관리자 화면의 최근 목록. 선두가 user_id 라 user_id 단독 인덱스는 따로 두지 않는다.
create index if not exists ai_questions_user_asked_idx
  on public.ai_questions (user_id, asked_at desc);

-- 본문에서 이 절에 내가 물어 둔 것을 찾는 자리 (saved 만 보인다)
create index if not exists ai_questions_verse_idx
  on public.ai_questions (user_id, book_code, chapter, verse_start);

-- 관리자 화면: 위기 건 먼저. 부분 인덱스라 전체 표가 커져도 값이 싸다.
create index if not exists ai_questions_crisis_idx
  on public.ai_questions (asked_at desc) where is_crisis;

-- 관리자 화면: 전체 최근 순
create index if not exists ai_questions_asked_idx
  on public.ai_questions (asked_at desc);

alter table public.ai_questions enable row level security;
-- 정책 없음: supabaseAdmin(service_role) 전용. 본인 조회는 항상 user_id 로 스코프한다.


-- ══════════════════════════════════════════════════════════════════
-- 2. 답 = 모델 하나가 준 한 칸
--    한 질문에 1개(single) 또는 3개(chorus). 실패한 칸도 행으로 남긴다 —
--    그날 Gemini 가 왜 빈 칸이었나를 뒤에 알 수 있어야 한다.
-- ══════════════════════════════════════════════════════════════════
create table if not exists public.ai_question_answers (
  id             bigint      generated by default as identity primary key,
  question_id    bigint      not null references public.ai_questions(id) on delete cascade,

  -- 화면의 칸. gemini · chatgpt · claude
  column_key     varchar(20) not null,
  -- 우리가 요청한 별칭 (gemini-flash · chatgpt · claude-sonnet)
  provider_alias varchar(40),
  -- 게이트웨이가 돌려준 실제 모델 이름. 칸 라벨의 진실은 이 값뿐이다 —
  -- 응답의 provider 필드는 계열명으로 정규화돼 와서(gemini-flash → "gemini")
  -- 강등된 답과 정상 답을 구분하지 못한다(2026-09-18 실측).
  model          varchar(80),

  ok             boolean     not null default false,
  -- **모델이 실제로 준 글을 그대로 남긴다.** 화면에 보인 것은 없는 구절 표시를 지운 판이지만,
  -- 모델이 없는 구절을 지어냈다는 사실은 기록에 남아야 잡을 수 있다(§B-5).
  content        text,
  -- 지운 주소. 이 값이 늘면 그 모델이 구절을 지어내고 있다는 뜻이다.
  removed_refs   text[],
  -- 실패 사유. MODEL_MISMATCH · EMPTY_RESPONSE · TIMEOUT · AI_ERROR 400 …
  error          text,

  input_tokens   integer,
  output_tokens  integer,
  elapsed_ms     integer,

  -- §B-6 '이 답이 이상합니다'
  reported       boolean     not null default false,
  report_reason  text,
  reported_at    timestamptz,

  created_at     timestamptz not null default now()
);

create index if not exists ai_question_answers_q_idx
  on public.ai_question_answers (question_id);

-- 관리자 화면: 신고된 답 먼저
create index if not exists ai_question_answers_reported_idx
  on public.ai_question_answers (reported_at desc) where reported;

-- 한 질문에 같은 칸이 두 번 들어가지 않는다(다시 묻기는 새 질문 행이다)
create unique index if not exists ai_question_answers_uniq
  on public.ai_question_answers (question_id, column_key);

alter table public.ai_question_answers enable row level security;


-- ══════════════════════════════════════════════════════════════════
-- 3. 관리자 열람 기록 — 열어 본 사실도 남긴다(§B-10)
--    교인에게 화면으로 알리지는 않는다(지휘부 2026-09-18).
-- ══════════════════════════════════════════════════════════════════
create table if not exists public.ai_question_views (
  id             bigint      generated by default as identity primary key,
  viewer_user_id text        not null,
  viewer_name    text,
  -- list = 목록을 열었다 · detail = 한 건을 펼쳤다 · delete = 지웠다 · export = 내려받았다
  action         varchar(20) not null,
  -- 목록 열람은 null
  question_id    bigint,
  -- 목록 열람 때의 조건(기간·검색어 등)을 남겨 두면 뒤에 무엇을 본 것인지 알 수 있다
  detail         text,
  viewed_at      timestamptz not null default now()
);

-- question_id 에 FK 를 걸지 않는다 — 질문이 지워진 뒤에도 지웠다는 기록이 남아야 한다.
create index if not exists ai_question_views_viewed_idx
  on public.ai_question_views (viewed_at desc);

alter table public.ai_question_views enable row level security;


-- ══════════════════════════════════════════════════════════════════
-- 4. 관리자 화면에서 고쳐 쓰는 네 가지 목록 (§B-11)
--    ① 이단 목록 ② 가정교회 자료 ③ 위기 상담 창구 ④ 삶공부 과정 이름
--    교리 기준 본문은 저장소 문서에 그대로 둔다 — 여기에는 자주 바뀌는 것만.
-- ══════════════════════════════════════════════════════════════════
create table if not exists public.qa_lists (
  id         bigint      generated by default as identity primary key,
  -- heresy · housechurch · crisis · lifestudy
  kind       varchar(20) not null,
  sort_order smallint    not null default 0,
  -- 이단 목록이면 단체명, 위기 창구면 창구 이름, 삶공부면 과정 이름
  title      text        not null,
  -- 이단 목록이면 무엇이 갈라지는가, 위기 창구면 번호와 여는 시간
  body       text,
  -- 사람만 보는 근거·출처(프롬프트에 넣지 않는다)
  note       text,
  enabled    boolean     not null default true,
  updated_at timestamptz not null default now(),
  updated_by text
);

create index if not exists qa_lists_kind_idx
  on public.qa_lists (kind, sort_order);

-- 같은 갈래에 같은 제목을 두 번 넣지 않는다
create unique index if not exists qa_lists_kind_title_uniq
  on public.qa_lists (kind, title);

alter table public.qa_lists enable row level security;


-- ══════════════════════════════════════════════════════════════════
-- 5. 설교 색인 — 이 구절을 다룬 우리 교회 설교 카드 (docs/BIBLE_QA_SERMONS.md)
--    AI 에게 주지 않는다. 앱이 답 아래에 카드로만 붙인다.
-- ══════════════════════════════════════════════════════════════════
create table if not exists public.sermons (
  id           bigint      generated by default as identity primary key,
  preached_on  date        not null,
  title        text        not null,
  preacher     text,
  video_url    text,
  -- 파일의 -요약- 절. 카드에는 첫 문단만 보인다.
  summary      text,
  -- 파일의 -적용- 절. 카드에 보이지 않는다(지휘부 2026-09-18) — 3단계와 뒷날을 위해 담아만 둔다.
  applications text[],

  -- 드라이브 원본 추적. modified 가 새로울 때만 다시 들여온다.
  source_file_id     text,
  source_name        text,
  source_modified_at timestamptz,
  ingested_at        timestamptz not null default now()
);

-- 같은 설교를 두 번 넣지 않는다. 파일 이름이 바뀌어도 날짜+제목이면 같은 설교다.
create unique index if not exists sermons_date_title_uniq
  on public.sermons (preached_on, title);

create index if not exists sermons_preached_idx
  on public.sermons (preached_on desc);

-- 공개 자료다 — 비로그인 교인에게도 카드가 보여야 한다.
-- 그래도 RLS 를 켜고 정책은 두지 않는다: 읽기는 반드시 서버 라우트(supabaseAdmin)를 거친다.
-- (anon 정책을 열면 브라우저에서 직접 긁을 수 있게 되고, 그만큼 조회 패턴을 통제할 수 없다.)
alter table public.sermons enable row level security;


create table if not exists public.sermon_refs (
  id          bigint      generated by default as identity primary key,
  sermon_id   bigint      not null references public.sermons(id) on delete cascade,
  -- main = 머리글의 본문 · quoted = 요약·적용 안에 인용된 구절
  kind        varchar(10) not null default 'main',
  book_code   varchar(10) not null,
  chapter     smallint    not null,
  verse_start smallint,
  verse_end   smallint
);

-- 카드 조회의 유일한 진입 — 이 인덱스가 없으면 수 ms 전제가 깨진다.
create index if not exists sermon_refs_lookup_idx
  on public.sermon_refs (book_code, chapter);

create index if not exists sermon_refs_sermon_idx
  on public.sermon_refs (sermon_id);

-- 같은 설교에 같은 구절을 두 번 넣지 않는다. 절이 null 인 장 전체도 한 번만.
create unique index if not exists sermon_refs_uniq
  on public.sermon_refs (sermon_id, kind, book_code, chapter,
                         coalesce(verse_start, 0), coalesce(verse_end, 0));

alter table public.sermon_refs enable row level security;


create table if not exists public.sermon_ingest_runs (
  id         bigint      generated by default as identity primary key,
  ran_at     timestamptz not null default now(),
  -- cron · manual
  trigger    varchar(10) not null default 'cron',
  scanned    integer     not null default 0,
  inserted   integer     not null default 0,
  updated    integer     not null default 0,
  skipped    integer     not null default 0,
  -- 못 읽은 파일과 까닭. 조용히 넘기면 없는 설교가 되고 아무도 모른다.
  failures   jsonb,
  elapsed_ms integer,
  error      text
);

create index if not exists sermon_ingest_runs_ran_idx
  on public.sermon_ingest_runs (ran_at desc);

alter table public.sermon_ingest_runs enable row level security;


-- ══════════════════════════════════════════════════════════════════
-- 6. 목록 초기값 — 재가받은 문서의 내용을 그대로 심는다.
--    docs/BIBLE_QA_HERESY_LIST.md 목록 A · docs/BIBLE_QA_DOCTRINE.md §C 위기 창구.
--    뒤에는 관리자 화면에서 고친다. on conflict do nothing 이라 두 번 실행해도 덮어쓰지 않는다
--    (관리자가 고친 값을 마이그레이션 재실행이 되돌리면 안 된다).
-- ══════════════════════════════════════════════════════════════════

-- 이단 목록 (지휘부 2026-09-18 확정 — 안식교·인터콥·다락방 포함)
-- 회기·연도는 넣지 않는다. 주면 답에서 틀리게 인용한다(§9).
insert into public.qa_lists (kind, sort_order, title, body, note) values
  ('heresy', 1, '신천지예수교 증거장막성전',
   '성경을 비유로 풀어 자기 단체를 실상이라 하고, 교주를 구원의 자리에 둔다',
   '주요 장로교 교단 공통 규정'),
  ('heresy', 2, '통일교(세계평화통일가정연합)',
   '그리스도의 유일한 중보를 부인하고 교주 부부를 참부모로 세운다',
   '주요 교단 비기독교'),
  ('heresy', 3, '하나님의교회(안상홍증인회)',
   '사람을 하나님의 자리에 두고 성경 밖의 계시를 더한다',
   '주요 교단 이단'),
  ('heresy', 4, '여호와의증인',
   '삼위일체와 그리스도의 신성을 부인한다',
   '주요 교단 이단'),
  ('heresy', 5, '몰몬교(말일성도예수그리스도교회)',
   '성경 외의 경전을 더하고 삼위일체·그리스도의 신성을 달리 가르친다',
   '주요 교단 이단'),
  ('heresy', 6, '구원파 계열(기독교복음침례회 등)',
   '깨달음으로 구원이 완결된다고 하여 회개와 성화를 없앤다',
   '기성·고신·통합·합동·합신 이단'),
  ('heresy', 7, 'JMS(기독교복음선교회)',
   '교주를 그리스도의 자리에 두고 성경 밖의 계시를 더한다',
   '주요 교단 반기독교·이단'),
  ('heresy', 8, '제칠일안식일예수재림교(안식교)',
   '안식일 교리와 구원론에서 갈라지고, 창시자의 글을 성경에 준하는 권위로 둔다',
   '지휘부 2026-09-18 포함'),
  ('heresy', 9, '인터콥',
   '종말론과 계시 이해, 교회의 치리 밖에서 움직이는 교회론에서 갈라진다',
   '합신이 교단 최초로 이단 규정. 문구를 합신 결의문으로 맞출 일이 남았다'),
  ('heresy', 10, '다락방(류광수)',
   '구원 이해와 마귀·귀신론의 치우침에서 갈라진다',
   '여러 교단 이단 규정. 문구를 합신 결의문으로 맞출 일이 남았다')
on conflict (kind, title) do nothing;

-- 위기 상담 창구 (지휘부 2026-09-18 확정). 2026-09-18 공공 안내로 확인했다.
-- **반년마다 한 사람이 다시 확인한다.** 문자·채팅 창구 확인은 아직 남았다.
insert into public.qa_lists (kind, sort_order, title, body, note) values
  ('crisis', 1, '자살예방 상담', '109 · 24시간 365일',
   '2024-01-01 부터 흩어져 있던 자살예방 상담전화가 109 로 통합(보건복지부)'),
  ('crisis', 2, '응급 구조·구급', '119 · 24시간', null),
  ('crisis', 3, '범죄·즉시 위험 · 아동학대 신고', '112 · 24시간',
   '아동학대 신고는 112 로 받는다'),
  ('crisis', 4, '정신건강 위기상담', '1577-0199 · 24시간',
   '109 통합 뒤에도 그대로 운영(국립정신건강센터)'),
  ('crisis', 5, '여성긴급전화(가정폭력·성폭력)', '1366 · 24시간', '종전대로 운영'),
  ('crisis', 6, '청소년 상담', '1388 · 24시간', '종전대로 운영'),
  ('crisis', 7, '노인학대 신고', '1577-1389 · 가까운 지역 기관으로 연결',
   '중앙노인보호전문기관')
on conflict (kind, title) do nothing;

-- 삶공부 과정 이름(kind='lifestudy')은 **넣지 않는다** — 예봄교회가 실제로 여는 과정만
-- 남기기로 했고 아직 확인되지 않았다(docs/BIBLE_QA_HOUSECHURCH.md 확인 항목).
-- 관리자 화면에서 넣으면 가정교회 자료를 붙이는 낱말 판별에 곧 쓰인다.


-- ══════════════════════════════════════════════════════════════════
-- 실행 뒤 확인 — RLS 가 정말 켜졌는지 눈으로 본다.
-- 일곱 표 모두 rls=true · policies=0 이어야 한다.
-- ══════════════════════════════════════════════════════════════════
-- select c.relname, c.relrowsecurity as rls,
--        (select count(*) from pg_policies p where p.tablename = c.relname) as policies
--   from pg_class c join pg_namespace n on n.oid = c.relnamespace
--  where n.nspname = 'public'
--    and c.relname in ('ai_questions','ai_question_answers','ai_question_views',
--                      'qa_lists','sermons','sermon_refs','sermon_ingest_runs')
--  order by c.relname;


-- ══════════════════════════════════════════════════════════════════
-- 7. 두 단계로 나누며 더한 열 (2026-09-18, Supabase 에 적용함: bible_qa_two_phase_columns)
--    1단계(/api/bible-qa)가 선별·기록하고, 2단계(/api/bible-qa/answer)가 칸마다 따로 답한다.
--    모두 nullable 로 더하기만 한다.
-- ══════════════════════════════════════════════════════════════════
-- 1단계가 고른 칸. 2단계는 여기 있는 칸에만 답한다(한 칸만 물었는데 세 칸을 받아 가지 못하게).
-- 위기·거절이면 비워 둔다 — 2단계가 모델을 부르지 않는 표시다.
alter table public.ai_questions add column if not exists columns  text[];
-- 선별이 걸린 시간과 모델이 돌려준 글자. 선별이 왜 실패했는지(시간 초과인지) 뒤에 알 수 있어야 한다.
alter table public.ai_questions add column if not exists gate_ms  integer;
alter table public.ai_questions add column if not exists gate_raw text;
-- 안전망(lib/bibleQa/crisisSignal.ts)이 1인칭 위기 말을 보았는가.
-- 선별이 실패했는데 이 값이 true 면 위기로 막았다는 뜻이다.
alter table public.ai_questions add column if not exists local_signal boolean;
notify pgrst, 'reload schema';
