-- 말씀의삶 — 성경읽기진도표 91회차 (단계 2)
--
-- 회차 완료는 저장하지 않는다. 기존 reading_progress(장 단위 자동 기록)에서 파생 계산한다.
-- 이 테이블이 담는 것은 **자동으로 알 수 없는 것 하나** — "종이 성경으로 읽었다"는 수동 표시다.
--
-- 공통 정책 (scripts/migration-login-features.sql 과 동일)
--  * user_id 는 saint.yebom.org 의 text id. Supabase Auth 를 쓰지 않으므로 auth.uid() 는 항상 null.
--  * 그래서 RLS 를 켜되 정책은 두지 않는다 = anon/authenticated 는 아무것도 못 읽고 못 쓴다.
--    서버(supabaseAdmin, service_role)만 접근하며 항상 user_id 로 스코프한다.
--    **enable row level security 를 빠뜨리면 anon 키로 전 교인의 체크 기록이 노출된다.**
--  * 쓰기는 SELECT-then-INSERT. UNIQUE 인덱스는 동시 요청 백스탑.
--  * 멱등 — 여러 번 실행해도 안전하다.

create table if not exists public.reading_unit_checks (
  id         bigint generated by default as identity primary key,
  user_id    text        not null,
  -- 지금은 yebom91 하나뿐이지만, 조회 시 반드시 이 컬럼으로 필터한다.
  -- default 는 INSERT 때만 걸리므로 필터를 생략하면 나중에 플랜이 늘 때 섞인다.
  plan_id    varchar(20) not null default 'yebom91',
  seq        smallint    not null,
  checked_at timestamptz not null default now()
);

-- 조회 커버 겸 동시 요청 백스탑. 선두가 user_id 라 user_id 단독 인덱스는 따로 두지 않는다.
create unique index if not exists reading_unit_checks_unique
  on public.reading_unit_checks (user_id, plan_id, seq);

alter table public.reading_unit_checks enable row level security;
