-- ============================================================
-- 로그인 전용 기능 마이그레이션 (2026-06-11)
--   A. reading_progress — 통독 진도
--   B. verse_notes      — 묵상 노트·하이라이트
--   E. user_state       — 기기간 동기화 (책갈피 / TTS 이어듣기)
--
-- 공통 정책 (scraps 패턴):
--  - user_id 는 saint.yebom.org user_id (text). Supabase Auth 미사용.
--  - 앱은 iron-session 인증이라 Supabase auth.uid() 가 항상 null →
--    RLS enable + 정책 없음 = anon/authenticated 클라이언트 직접 접근 전면 차단.
--    API 라우트의 service_role(supabaseAdmin) 만 우회 접근하며 항상 user_id 로 스코프.
--  - 쓰기는 SELECT-then-UPDATE/INSERT (UNIQUE 가 race 백스탑).
-- 멱등 작성(if not exists) — 재실행 안전.
-- ============================================================

-- ─── A. reading_progress (통독 진도) ──────────────────────────
create table if not exists public.reading_progress (
  id         bigint generated by default as identity primary key,
  user_id    text        not null,
  book_code  varchar(10) not null,
  chapter    smallint    not null,
  version    varchar(10),                       -- 읽은 시점 역본 (참고용, UNIQUE 키 아님)
  read_at    timestamptz not null default now()
);
-- 같은 장을 어느 역본으로 읽든 1독 1회 (version 은 UNIQUE 키에서 제외)
create unique index if not exists reading_progress_unique_per_user
  on public.reading_progress (user_id, book_code, chapter);
create index if not exists reading_progress_user_idx
  on public.reading_progress (user_id);
alter table public.reading_progress enable row level security;

-- ─── B. verse_notes (묵상 노트·하이라이트) ────────────────────
create table if not exists public.verse_notes (
  id         bigint generated by default as identity primary key,
  user_id    text        not null,
  user_name  text,
  book_code  varchar(10) not null,
  chapter    smallint    not null,
  verse      smallint    not null,
  color      varchar(16),                       -- null = 메모만
  note       text,                              -- null = 하이라이트만 (둘 다 null 이면 행 삭제)
  version    varchar(10),                       -- 저장 시점 역본 (표시 참고용, UNIQUE 키 아님)
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
-- 절 단위 1행
create unique index if not exists verse_notes_unique_per_user
  on public.verse_notes (user_id, book_code, chapter, verse);
-- 장 단위 페치 인덱스
create index if not exists verse_notes_user_chapter_idx
  on public.verse_notes (user_id, book_code, chapter);
alter table public.verse_notes enable row level security;

-- ─── E. user_state (기기간 동기화) ────────────────────────────
-- key='bookmarks' | 'tts_resume' 등. value 는 클라이언트 상태 JSON 그대로.
create table if not exists public.user_state (
  user_id    text        not null,
  key        varchar(40) not null,
  value      jsonb       not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, key)
);
alter table public.user_state enable row level security;
