-- 말씀의삶 — 함께 읽기 그룹 (단계 4)
--
-- 목적은 순위표가 아니라 **동행 확인**이다. 같은 진도표를 읽는 사람들이
-- 서로 몇 회차인지 보는 것까지가 범위다. 벌점·독촉·미읽음 알림은 두지 않는다.
--
-- 진도 자체는 저장하지 않는다. reading_progress + reading_unit_checks 에서
-- 회차 완료 수를 파생 계산한다(lib/readingGroups.ts groupStandings).
-- 그룹 테이블은 "누가 어느 모임에 속했는가" 만 담는다.
--
-- 공통 정책 (scripts/migration-login-features.sql 과 동일)
--  * user_id 는 saint.yebom.org 의 text id. Supabase Auth 를 쓰지 않으므로 auth.uid() 는 항상 null.
--  * 그래서 RLS 를 켜되 정책은 두지 않는다 = anon/authenticated 는 아무것도 못 읽고 못 쓴다.
--    서버(supabaseAdmin, service_role)만 접근한다.
--    **enable row level security 를 빠뜨리면 anon 키로 전 교인의 소속과 초대코드가 노출된다.**
--  * 멱등 — 여러 번 실행해도 안전하다.

create table if not exists public.reading_groups (
  id          bigint generated by default as identity primary key,
  name        text        not null,
  -- 초대코드는 서버가 만든다. 클라이언트가 정하게 두면 남의 그룹 이름을 선점할 수 있다.
  -- 혼동되는 O·0·I·1 을 뺀 32자 알파벳 6자리 (lib/readingGroups.ts CODE_ALPHABET).
  invite_code varchar(6)  not null unique,
  plan_id     varchar(20) not null default 'yebom91',
  created_by  text        not null,
  created_at  timestamptz not null default now()
);

create table if not exists public.reading_group_members (
  group_id  bigint      not null references public.reading_groups(id) on delete cascade,
  user_id   text        not null,
  -- 순위표에 띄울 이름. 세션의 표시 이름을 참여 시점에 복사해 둔다
  -- (교인 계정 테이블이 이 프로젝트에 없어 조인할 곳이 없다).
  user_name text,
  joined_at timestamptz not null default now(),
  -- 복합 PK 가 곧 "한 그룹에 한 번만" 제약이다. 별도 UNIQUE 를 두지 않는다.
  primary key (group_id, user_id)
);

-- "내가 속한 그룹" 조회용. PK 선두가 group_id 라 user_id 단독 조회를 커버하지 못한다.
create index if not exists reading_group_members_user_idx
  on public.reading_group_members (user_id);

alter table public.reading_groups        enable row level security;
alter table public.reading_group_members enable row level security;
