-- 말씀의삶 — 그룹마다 다른 진도표 (2026-09-20 지휘부)
--
-- 지금까지 진도표는 파일에 박힌 하나뿐이었다(`lib/plans/yebom91.ts`, 화면 이름 **표준진도표**).
-- 이제 교인이 진도표를 만들어 DB 에 두고, 그룹이 자기 진도표를 고른다.
--
-- 정한 것(지휘부 2026-09-20)
--  * 표준진도표는 **파일에 그대로 둔다** — 재가받은 데이터라 git 이력과 검증 스크립트(verify:plan)가 붙어 있다.
--    DB 에는 새로 만든 진도표만 들어온다. 두 갈래를 `lib/plans/registry.ts` 의 로더가 합쳐 준다.
--  * 진도표는 **틀(템플릿)이라 서로 보인다.** 진도(누가 어디까지 읽었는지)는 지금처럼 그룹 안에서만 보인다.
--    만든 사람이 '나만 쓰기' 를 고르면 목록에서 빠진다.
--  * 읽기 시작한 진도표는 **범위를 잠그고**(`locked_at`) 고치려면 복사한다. 이름·설명은 계속 고칠 수 있다.
--  * 지우기 — 쓰는 그룹이 없으면 삭제, 있으면 목록에서만 내린다(`hidden_at`).
--    수퍼어드민이 끝내 지우면 **그 그룹의 진도표는 해제된다**(`plan_id = null`).
--    다른 진도표로 **임의로 옮기지 않는다** — 그룹이 무엇을 읽는지는 그룹이 정한다.
--
-- 공통 정책 (scripts/migration-reading-groups.sql 과 동일)
--  * user_id 는 saint.yebom.org 의 text id. Supabase Auth 를 쓰지 않으므로 auth.uid() 는 항상 null.
--  * 그래서 RLS 를 켜되 정책은 두지 않는다 = anon/authenticated 는 아무것도 못 읽고 못 쓴다.
--    서버(supabaseAdmin, service_role)만 접근한다.
--    **enable row level security 를 빠뜨리면 anon 키로 아무나 진도표를 고치고 지울 수 있다.**
--  * 멱등 — 여러 번 실행해도 안전하다.

-- ─── 1. 진도표 ────────────────────────────────────────────────
create table if not exists public.reading_plans (
  id            bigint generated by default as identity primary key,
  -- 그룹·체크 기록이 참조하는 키. 서버가 'p12' 꼴로 만든다(파일 진도표는 'yebom91').
  slug          varchar(24) not null unique,
  name          text        not null,
  description   text,
  -- PlanUnit[] 를 그대로 담는다 — 엔진(lib/plans/engine.ts)이 파일 진도표와 똑같이 읽는다.
  -- 진도표는 늘 통째로 읽고 통째로 저장한다. 회차를 별도 표로 쪼개면 한 번 읽는 데 91행을 긁어야 한다.
  units         jsonb       not null,
  -- 목록에서 보여 줄 요약값(회차 수·장 수). units 를 파싱하지 않고 목록을 그릴 수 있게 둔다.
  unit_count    smallint    not null default 0,
  chapter_count smallint    not null default 0,
  -- public = 목록에 보인다(남이 복사할 수 있다) · private = 만든 사람만 본다
  visibility    varchar(10) not null default 'public',
  created_by      text not null,
  -- 목록에 '만든 이' 로 띄운다. 교인 계정 표가 이 프로젝트에 없어 조인할 곳이 없다(그룹 표와 같은 방식).
  created_by_name text,
  -- 복사해서 만든 것이면 원본. 원본이 지워져도 복사본은 남는다.
  copied_from   bigint      references public.reading_plans(id) on delete set null,
  -- 누군가 이 진도표로 회차를 체크한 순간 잠근다. 범위는 잠긴 뒤 못 고친다(복사해서 새로 만든다).
  locked_at     timestamptz,
  -- 목록에서 내림 — 쓰는 그룹이 있어 지우지 못할 때. 쓰던 그룹은 그대로 읽는다.
  hidden_at     timestamptz,
  -- 신고(이름·회차 이름이 이상할 때). 관리자가 목록에서 바로 본다.
  report_count  smallint    not null default 0,
  report_reason text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- 공개 목록 — 숨긴 것을 빼고 최근 것부터.
create index if not exists reading_plans_public_idx
  on public.reading_plans (visibility, hidden_at, updated_at desc);

-- 내가 만든 것.
create index if not exists reading_plans_owner_idx
  on public.reading_plans (created_by, updated_at desc);

alter table public.reading_plans enable row level security;

-- ─── 2. 이미 있는 표에 자리 넓히기 ────────────────────────────
-- plan_id 는 varchar(20) 이었다. 파일 진도표 하나('yebom91')만 있던 시절의 폭이라 넓힌다.
alter table public.reading_groups      alter column plan_id type text;
alter table public.reading_unit_checks alter column plan_id type text;

-- 그룹의 진도표가 **없을 수 있다** — 쓰던 진도표가 지워지면 해제된다(지휘부: 임의로 옮기지 않는다).
-- default 'yebom91' 은 그대로 둔다. 새로 만드는 그룹은 고르지 않으면 표준진도표를 읽는다.
alter table public.reading_groups      alter column plan_id drop not null;

-- 그룹이 어떤 진도표를 쓰는지 세는 조회(지울 수 있는가 판단). 선두가 plan_id 인 인덱스가 없었다.
create index if not exists reading_groups_plan_idx
  on public.reading_groups (plan_id);

-- 진도표별 체크 조회. 기존 UNIQUE(user_id, plan_id, seq) 는 선두가 user_id 라
-- "이 진도표를 누가 읽기 시작했나"(잠금 판정)를 커버하지 못한다.
create index if not exists reading_unit_checks_plan_idx
  on public.reading_unit_checks (plan_id);
